#!/bin/bash
# -*- shell-script -*-

PARAMS=""
EMACS="default"
EMACS_BIN=""

while (( "$#" )); do
  case "$1" in
    -x|--with-emacs)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
	  EMACS=$2
	  shift 2
      else
        echo "Error: Argument for $1 is missing" >&2
        exit 1
      fi
      ;;
    *) # preserve positional arguments
      PARAMS="$PARAMS $1"
      shift
      ;;
  esac
done

if [[ ${EMACS} == "27" ]]; then
	EMACS_BIN="/usr/local/bin/emacs"
fi
if [[ ${EMACS} == "28" ]]; then
	EMACS_BIN="/usr/local/emacs/master-native/bin/emacs"
fi

if [[ ${EMACS} == "default" ]]; then
    EMACS_BIN="/usr/bin/emacs"
fi

if [[ -z ${EMACS_BIN} ]]; then
    echo "Error: ${EMACS} is not a known emacs binary" >&2
    exit 2
fi
# set positional arguments in their proper place
eval set -- "$PARAMS"

export EMACS

# TODO add command line flag to select binary
${EMACS_BIN} "$@"
